server:
  port: 8090

spring:
  application:
    name: admin-service
  config:
    import: "optional:configserver:http://config-service:8888"

  cloud:
    config:
      discovery:
        service-id: config-service
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

spring.boot.admin:
  discovery:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all Actuator endpoints
  endpoint:
    health:
      show-details: always

logging:
  level:
    de.codecentric.boot.admin: DEBUG
    org.springframework.cloud: DEBUG