spring:
  application:
    name: admin-service
  config:
    import: "optional:configserver:"

  cloud:
    config:
      discovery:
        service-id: config-service
        enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

spring.boot.admin:
  discovery:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all Actuator endpoints
  endpoint:
    health:
      show-details: always

logging:
  level:
    de.codecentric.boot.admin: DEBUG
    org.springframework.cloud: DEBUG