server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: helloeveryoneiamyogeshkumarandthisismysecretkey

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all Actuator endpoints
  endpoint:
    health:
      show-details: always