eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all Actuator endpoints
  endpoint:
    health:
      show-details: always