server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # Applies to all routes
            allowedOrigins: "http://bankingapp-ui:3000" # Frontend origin
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/bankingapp/api/accounts/**
          filters:
            - StripPrefix=2
            - name: JwtFilter

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/bankingapp/api/transactions/**
          filters:
            - StripPrefix=2
            - name: JwtFilter


        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/bankingapp/api/fund-transfer/**
          filters:
            - StripPrefix=2
            - name: JwtFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/bankingapp/api/notifications/**
          filters:
            - StripPrefix=2

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/bankingapp/api/auth/**
          filters:
            - StripPrefix=2


#  devtools:
#    restart:
#      poll-interval: 2s
#      quiet-period: 1s

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: helloeveryoneiamyogeshkumarandthisismysecretkey

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.blueyonder.bankingapp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all Actuator endpoints
  endpoint:
    health:
      show-details: always