server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/bankingapp/api/accounts/**
          filters:
            - StripPrefix=2
            - name: JwtFilter

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/bankingapp/api/transactions/**
          filters:
            - StripPrefix=2
            - name: JwtFilter


        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/bankingapp/api/fundTransfers/**
          filters:
            - StripPrefix=2
            - name: JwtFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/bankingapp/api/notifications/**
          filters:
            - StripPrefix=2

        - id: auth-service-public
          uri: lb://auth-service
          predicates:
            - Path=/bankingapp/api/auth/login, /bankingapp/api/auth/signup, /bankingapp/api/auth/adminlogin
          filters:
            - StripPrefix=2

        - id: auth-service-secure
          uri: lb://auth-service
          predicates:
            - Path=/bankingapp/api/auth/user
          filters:
            - StripPrefix=2
            - name: JwtFilter


#  devtools:
#    restart:
#      poll-interval: 2s
#      quiet-period: 1s

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: helloeveryoneiamyogeshkumarandthisismysecretkey

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.blueyonder.bankingapp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all Actuator endpoints
  endpoint:
    health:
      show-details: always