spring:
  application:
    name: transaction-service

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    #    root: WARN
    #    com.blueyonder.bankingapp: INFO
    #    org.springframework: WARN
    #    org.hibernate: WARN
    org.springframework.boot.devtools: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all Actuator endpoints
  endpoint:
    health:
      show-details: always